# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gameroom.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 605)
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 1000, 611))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.bgwidget.setFont(font)
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.0511364, y1:0.068, x2:0.813, y2:0.823864, stop:0 rgba(209, 107, 165, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: qlineargradient(spread:pad, x1:0.142, y1:0.130818, x2:0.9375, y2:0.932, stop:0 rgba(10, 9, 16, 255), stop:1 rgba(73, 0, 126, 255));\n"
"    background-color: qlineargradient(spread:pad, x1:0.0454545, y1:0.125, x2:0.954545, y2:0.915, stop:0 rgba(186, 166, 165, 255), stop:1 rgba(222, 191, 181, 255));\n"
"    background-color: qlineargradient(spread:pad, x1:0.057, y1:0.0625, x2:0.988636, y2:0.96, stop:0 rgba(82, 151, 172, 255), stop:1 rgba(166, 198, 193, 255));\n"
"}\n"
"")
        self.bgwidget.setObjectName("bgwidget")
        self.otherusernamelabel = QtWidgets.QLabel(self.bgwidget)
        self.otherusernamelabel.setGeometry(QtCore.QRect(720, 40, 200, 23))
        self.otherusernamelabel.setStyleSheet("font: 14pt \"Century Gothic\";\n"
"color: rgb(154, 133, 143, 255);")
        self.otherusernamelabel.setText("")
        self.otherusernamelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.otherusernamelabel.setObjectName("otherusernamelabel")
        self.exitbutton = QtWidgets.QPushButton(self.bgwidget)
        self.exitbutton.setGeometry(QtCore.QRect(11, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.exitbutton.setFont(font)
        self.exitbutton.setStyleSheet("color: rgb(230, 224, 207);\n"
"font: 10pt \"Century Gothic\";\n"
"background-color:rgba(0,0,0,0);")
        self.exitbutton.setObjectName("exitbutton")
        self.column0 = QtWidgets.QPushButton(self.bgwidget)
        self.column0.setGeometry(QtCore.QRect(180, 75, 90, 480))
        self.column0.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 20);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(225,225,225,45);\n"
"}\n"
"")
        self.column0.setText("")
        self.column0.setObjectName("column0")
        self.column1 = QtWidgets.QPushButton(self.bgwidget)
        self.column1.setGeometry(QtCore.QRect(270, 75, 90, 480))
        self.column1.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 20);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(225,225,225,45);\n"
"}\n"
"")
        self.column1.setText("")
        self.column1.setObjectName("column1")
        self.column2 = QtWidgets.QPushButton(self.bgwidget)
        self.column2.setGeometry(QtCore.QRect(360, 75, 90, 480))
        self.column2.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 20);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(225,225,225,45);\n"
"}\n"
"")
        self.column2.setText("")
        self.column2.setObjectName("column2")
        self.column3 = QtWidgets.QPushButton(self.bgwidget)
        self.column3.setGeometry(QtCore.QRect(450, 75, 90, 480))
        self.column3.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 20);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(225,225,225,45);\n"
"}\n"
"")
        self.column3.setText("")
        self.column3.setObjectName("column3")
        self.column4 = QtWidgets.QPushButton(self.bgwidget)
        self.column4.setGeometry(QtCore.QRect(540, 75, 90, 480))
        self.column4.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 20);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(225,225,225,45);\n"
"}\n"
"")
        self.column4.setText("")
        self.column4.setObjectName("column4")
        self.column5 = QtWidgets.QPushButton(self.bgwidget)
        self.column5.setGeometry(QtCore.QRect(630, 75, 90, 480))
        self.column5.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 20);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(225,225,225,45);\n"
"}\n"
"")
        self.column5.setText("")
        self.column5.setObjectName("column5")
        self.column6 = QtWidgets.QPushButton(self.bgwidget)
        self.column6.setGeometry(QtCore.QRect(720, 75, 90, 480))
        self.column6.setStyleSheet("QPushButton{\n"
"background-color: rgba(255, 255, 255, 20);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(225,225,225,45);\n"
"}\n"
"")
        self.column6.setText("")
        self.column6.setObjectName("column6")
        self.cell00 = QtWidgets.QLabel(self.bgwidget)
        self.cell00.setGeometry(QtCore.QRect(190, 80, 70, 70))
        self.cell00.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell00.setText("")
        self.cell00.setObjectName("cell00")
        self.cell01 = QtWidgets.QLabel(self.bgwidget)
        self.cell01.setGeometry(QtCore.QRect(190, 160, 70, 70))
        self.cell01.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell01.setText("")
        self.cell01.setObjectName("cell01")
        self.cell02 = QtWidgets.QLabel(self.bgwidget)
        self.cell02.setGeometry(QtCore.QRect(190, 240, 70, 70))
        self.cell02.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell02.setText("")
        self.cell02.setObjectName("cell02")
        self.cell03 = QtWidgets.QLabel(self.bgwidget)
        self.cell03.setGeometry(QtCore.QRect(190, 320, 70, 70))
        self.cell03.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell03.setText("")
        self.cell03.setObjectName("cell03")
        self.cell04 = QtWidgets.QLabel(self.bgwidget)
        self.cell04.setGeometry(QtCore.QRect(190, 400, 70, 70))
        self.cell04.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell04.setText("")
        self.cell04.setObjectName("cell04")
        self.cell05 = QtWidgets.QLabel(self.bgwidget)
        self.cell05.setGeometry(QtCore.QRect(190, 480, 70, 70))
        self.cell05.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell05.setText("")
        self.cell05.setObjectName("cell05")
        self.cell10 = QtWidgets.QLabel(self.bgwidget)
        self.cell10.setGeometry(QtCore.QRect(280, 80, 70, 70))
        self.cell10.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell10.setText("")
        self.cell10.setObjectName("cell10")
        self.cell13 = QtWidgets.QLabel(self.bgwidget)
        self.cell13.setGeometry(QtCore.QRect(280, 320, 70, 70))
        self.cell13.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell13.setText("")
        self.cell13.setObjectName("cell13")
        self.cell11 = QtWidgets.QLabel(self.bgwidget)
        self.cell11.setGeometry(QtCore.QRect(280, 160, 70, 70))
        self.cell11.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell11.setText("")
        self.cell11.setObjectName("cell11")
        self.cell12 = QtWidgets.QLabel(self.bgwidget)
        self.cell12.setGeometry(QtCore.QRect(280, 240, 70, 70))
        self.cell12.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell12.setText("")
        self.cell12.setObjectName("cell12")
        self.cell15 = QtWidgets.QLabel(self.bgwidget)
        self.cell15.setGeometry(QtCore.QRect(280, 480, 70, 70))
        self.cell15.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell15.setText("")
        self.cell15.setObjectName("cell15")
        self.cell14 = QtWidgets.QLabel(self.bgwidget)
        self.cell14.setGeometry(QtCore.QRect(280, 400, 70, 70))
        self.cell14.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell14.setText("")
        self.cell14.setObjectName("cell14")
        self.cell22 = QtWidgets.QLabel(self.bgwidget)
        self.cell22.setGeometry(QtCore.QRect(370, 240, 70, 70))
        self.cell22.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell22.setText("")
        self.cell22.setObjectName("cell22")
        self.cell21 = QtWidgets.QLabel(self.bgwidget)
        self.cell21.setGeometry(QtCore.QRect(370, 160, 70, 70))
        self.cell21.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell21.setText("")
        self.cell21.setObjectName("cell21")
        self.cell20 = QtWidgets.QLabel(self.bgwidget)
        self.cell20.setGeometry(QtCore.QRect(370, 80, 70, 70))
        self.cell20.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell20.setText("")
        self.cell20.setObjectName("cell20")
        self.cell25 = QtWidgets.QLabel(self.bgwidget)
        self.cell25.setGeometry(QtCore.QRect(370, 480, 70, 70))
        self.cell25.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell25.setText("")
        self.cell25.setObjectName("cell25")
        self.cell24 = QtWidgets.QLabel(self.bgwidget)
        self.cell24.setGeometry(QtCore.QRect(370, 400, 70, 70))
        self.cell24.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell24.setText("")
        self.cell24.setObjectName("cell24")
        self.cell23 = QtWidgets.QLabel(self.bgwidget)
        self.cell23.setGeometry(QtCore.QRect(370, 320, 70, 70))
        self.cell23.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell23.setText("")
        self.cell23.setObjectName("cell23")
        self.cell35 = QtWidgets.QLabel(self.bgwidget)
        self.cell35.setGeometry(QtCore.QRect(460, 480, 70, 70))
        self.cell35.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell35.setText("")
        self.cell35.setObjectName("cell35")
        self.cell34 = QtWidgets.QLabel(self.bgwidget)
        self.cell34.setGeometry(QtCore.QRect(460, 400, 70, 70))
        self.cell34.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell34.setText("")
        self.cell34.setObjectName("cell34")
        self.cell33 = QtWidgets.QLabel(self.bgwidget)
        self.cell33.setGeometry(QtCore.QRect(460, 320, 70, 70))
        self.cell33.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell33.setText("")
        self.cell33.setObjectName("cell33")
        self.cell32 = QtWidgets.QLabel(self.bgwidget)
        self.cell32.setGeometry(QtCore.QRect(460, 240, 70, 70))
        self.cell32.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell32.setText("")
        self.cell32.setObjectName("cell32")
        self.cell31 = QtWidgets.QLabel(self.bgwidget)
        self.cell31.setGeometry(QtCore.QRect(460, 160, 70, 70))
        self.cell31.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell31.setText("")
        self.cell31.setObjectName("cell31")
        self.cell30 = QtWidgets.QLabel(self.bgwidget)
        self.cell30.setGeometry(QtCore.QRect(460, 80, 70, 70))
        self.cell30.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell30.setText("")
        self.cell30.setObjectName("cell30")
        self.cell45 = QtWidgets.QLabel(self.bgwidget)
        self.cell45.setGeometry(QtCore.QRect(550, 480, 70, 70))
        self.cell45.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell45.setText("")
        self.cell45.setObjectName("cell45")
        self.cell40 = QtWidgets.QLabel(self.bgwidget)
        self.cell40.setGeometry(QtCore.QRect(550, 80, 70, 70))
        self.cell40.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell40.setText("")
        self.cell40.setObjectName("cell40")
        self.cell44 = QtWidgets.QLabel(self.bgwidget)
        self.cell44.setGeometry(QtCore.QRect(550, 400, 70, 70))
        self.cell44.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell44.setText("")
        self.cell44.setObjectName("cell44")
        self.cell43 = QtWidgets.QLabel(self.bgwidget)
        self.cell43.setGeometry(QtCore.QRect(550, 320, 70, 70))
        self.cell43.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell43.setText("")
        self.cell43.setObjectName("cell43")
        self.cell41 = QtWidgets.QLabel(self.bgwidget)
        self.cell41.setGeometry(QtCore.QRect(550, 160, 70, 70))
        self.cell41.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell41.setText("")
        self.cell41.setObjectName("cell41")
        self.cell42 = QtWidgets.QLabel(self.bgwidget)
        self.cell42.setGeometry(QtCore.QRect(550, 240, 70, 70))
        self.cell42.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell42.setText("")
        self.cell42.setObjectName("cell42")
        self.cell54 = QtWidgets.QLabel(self.bgwidget)
        self.cell54.setGeometry(QtCore.QRect(640, 400, 70, 70))
        self.cell54.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell54.setText("")
        self.cell54.setObjectName("cell54")
        self.cell53 = QtWidgets.QLabel(self.bgwidget)
        self.cell53.setGeometry(QtCore.QRect(640, 320, 70, 70))
        self.cell53.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell53.setText("")
        self.cell53.setObjectName("cell53")
        self.cell52 = QtWidgets.QLabel(self.bgwidget)
        self.cell52.setGeometry(QtCore.QRect(640, 240, 70, 70))
        self.cell52.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell52.setText("")
        self.cell52.setObjectName("cell52")
        self.cell51 = QtWidgets.QLabel(self.bgwidget)
        self.cell51.setGeometry(QtCore.QRect(640, 160, 70, 70))
        self.cell51.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell51.setText("")
        self.cell51.setObjectName("cell51")
        self.cell50 = QtWidgets.QLabel(self.bgwidget)
        self.cell50.setGeometry(QtCore.QRect(640, 80, 70, 70))
        self.cell50.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell50.setText("")
        self.cell50.setObjectName("cell50")
        self.cell55 = QtWidgets.QLabel(self.bgwidget)
        self.cell55.setGeometry(QtCore.QRect(640, 480, 70, 70))
        self.cell55.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell55.setText("")
        self.cell55.setObjectName("cell55")
        self.cell61 = QtWidgets.QLabel(self.bgwidget)
        self.cell61.setGeometry(QtCore.QRect(730, 160, 70, 70))
        self.cell61.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell61.setText("")
        self.cell61.setObjectName("cell61")
        self.cell60 = QtWidgets.QLabel(self.bgwidget)
        self.cell60.setGeometry(QtCore.QRect(730, 80, 70, 70))
        self.cell60.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell60.setText("")
        self.cell60.setObjectName("cell60")
        self.cell65 = QtWidgets.QLabel(self.bgwidget)
        self.cell65.setGeometry(QtCore.QRect(730, 480, 70, 70))
        self.cell65.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell65.setText("")
        self.cell65.setObjectName("cell65")
        self.cell64 = QtWidgets.QLabel(self.bgwidget)
        self.cell64.setGeometry(QtCore.QRect(730, 400, 70, 70))
        self.cell64.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"")
        self.cell64.setText("")
        self.cell64.setObjectName("cell64")
        self.cell63 = QtWidgets.QLabel(self.bgwidget)
        self.cell63.setGeometry(QtCore.QRect(730, 320, 70, 70))
        self.cell63.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"\n"
"\n"
"")
        self.cell63.setText("")
        self.cell63.setObjectName("cell63")
        self.cell62 = QtWidgets.QLabel(self.bgwidget)
        self.cell62.setGeometry(QtCore.QRect(730, 240, 70, 70))
        self.cell62.setStyleSheet("border-radius:35px;\n"
"background-color: rgba(255, 255, 255, 20);\n"
"\n"
"")
        self.cell62.setText("")
        self.cell62.setObjectName("cell62")
        self.yourusernamelabel = QtWidgets.QLabel(self.bgwidget)
        self.yourusernamelabel.setGeometry(QtCore.QRect(70, 40, 200, 23))
        self.yourusernamelabel.setStyleSheet("font: 14pt \"Century Gothic\";\n"
"color: rgba(243,211,193,255);\n"
"")
        self.yourusernamelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yourusernamelabel.setObjectName("yourusernamelabel")
        self.idlabel = QtWidgets.QLabel(self.bgwidget)
        self.idlabel.setGeometry(QtCore.QRect(410, 30, 180, 20))
        self.idlabel.setStyleSheet("font: 12pt \"Century Gothic\";\n"
"color: rgb(255, 0, 4);\n"
"color: rgb(230, 224, 207);\n"
"")
        self.idlabel.setText("")
        self.idlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.idlabel.setObjectName("idlabel")
        self.errorlabel = QtWidgets.QLabel(self.bgwidget)
        self.errorlabel.setGeometry(QtCore.QRect(270, 40, 460, 20))
        self.errorlabel.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.errorlabel.setText("")
        self.errorlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorlabel.setObjectName("errorlabel")
        self.gameoverlabel = QtWidgets.QLabel(self.bgwidget)
        self.gameoverlabel.setGeometry(QtCore.QRect(370, 10, 260, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.gameoverlabel.setFont(font)
        self.gameoverlabel.setStyleSheet("font: 16pt \"Century Gothic\";\n"
"color: rgb(255, 0, 4);\n"
"color: rgb(222, 191, 181);")
        self.gameoverlabel.setText("")
        self.gameoverlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gameoverlabel.setObjectName("gameoverlabel")
        self.gamescorelabel = QtWidgets.QLabel(self.bgwidget)
        self.gamescorelabel.setGeometry(QtCore.QRect(370, 40, 260, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.gamescorelabel.setFont(font)
        self.gamescorelabel.setStyleSheet("font: 14pt \"Century Gothic\";\n"
"color: rgb(255, 0, 4);\n"
"color: rgb(222, 191, 181);")
        self.gamescorelabel.setText("")
        self.gamescorelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gamescorelabel.setObjectName("gamescorelabel")
        self.instructionslabel = QtWidgets.QLabel(self.bgwidget)
        self.instructionslabel.setGeometry(QtCore.QRect(270, 560, 460, 20))
        self.instructionslabel.setStyleSheet("color: rgb(117, 104, 104);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.instructionslabel.setText("")
        self.instructionslabel.setAlignment(QtCore.Qt.AlignCenter)
        self.instructionslabel.setObjectName("instructionslabel")
        self.otherusernamelabel.raise_()
        self.exitbutton.raise_()
        self.cell00.raise_()
        self.cell01.raise_()
        self.cell02.raise_()
        self.cell03.raise_()
        self.cell04.raise_()
        self.cell05.raise_()
        self.cell10.raise_()
        self.cell13.raise_()
        self.cell11.raise_()
        self.cell12.raise_()
        self.cell15.raise_()
        self.cell14.raise_()
        self.cell22.raise_()
        self.cell21.raise_()
        self.cell20.raise_()
        self.cell25.raise_()
        self.cell24.raise_()
        self.cell23.raise_()
        self.cell35.raise_()
        self.cell34.raise_()
        self.cell33.raise_()
        self.cell32.raise_()
        self.cell31.raise_()
        self.cell30.raise_()
        self.cell45.raise_()
        self.cell40.raise_()
        self.cell44.raise_()
        self.cell43.raise_()
        self.cell41.raise_()
        self.cell42.raise_()
        self.cell54.raise_()
        self.cell53.raise_()
        self.cell52.raise_()
        self.cell51.raise_()
        self.cell50.raise_()
        self.cell55.raise_()
        self.cell61.raise_()
        self.cell60.raise_()
        self.cell65.raise_()
        self.cell64.raise_()
        self.cell63.raise_()
        self.cell62.raise_()
        self.yourusernamelabel.raise_()
        self.idlabel.raise_()
        self.column0.raise_()
        self.column1.raise_()
        self.column2.raise_()
        self.column3.raise_()
        self.column4.raise_()
        self.column5.raise_()
        self.errorlabel.raise_()
        self.gameoverlabel.raise_()
        self.gamescorelabel.raise_()
        self.instructionslabel.raise_()
        self.column6.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.exitbutton.setText(_translate("Dialog", "EXIT"))
        self.yourusernamelabel.setText(_translate("Dialog", "usernamelabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
